services:
  mysql-db:
    image: mysql:8.0
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./convergence.sql:/docker-entrypoint-initdb.d/convergence.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend-java:
    build: 
      context: "./Api rest"
      dockerfile: dockerFile
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/${DB_NAME}?serverTimezone=UTC&useSSL=false
    depends_on:
      mysql-db:
        condition: service_healthy

  backend-js:
    build: 
      context: ./Backend
      dockerfile: dockerFile
    restart: on-failure
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    environment:
      - API_BASE_URL=http://backend-java:8080
      - DB_HOST=mysql-db
    depends_on:
      - backend-java

  frontend-angular:
    build: 
      context: ./Convergence
      dockerfile: dockerFile
    restart: on-failure
    ports:
      - "80:80"
    depends_on:
      - backend-java
      - backend-js

volumes:
  mysql-data:
